#!/bin/sh
# Script to fix the laptop input after power save.
synclient MaxTapTime=0 PalmDetect=1 HorizTwoFingerScroll=1 VertEdgeScroll=0 RightButtonAreaLeft=0 RightButtonAreaTop=0
/usr/bin/imwheel --kill
xset r rate 300 30
