#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"
repo="$(basename `git rev-parse --show-toplevel`)"

protected_branch="main"

if [ "$branch" = "$protected_branch" ] && [ "$repo" != "settings" ]; then
  echo "You can't commit directly to $protected_branch branch"
  exit 1
fi
